package br.com.brunocarvalhs.commons.theme

import androidx.compose.ui.graphics.Color

val SeedRed = Color(0xFFFF585D)
val PrimaryRed = Color(0xFFB6212F)
val OnPrimaryRed = Color(0xFFFFFFFF)
val PrimaryContainerRed = Color(0xFFFFDAD8)
val OnPrimaryContainerRed = Color(0xFF410006)
val SecondaryGreen = Color(0xFF006874)
val OnSecondaryGreen = Color(0xFFFFFFFF)
val SecondaryContainerGreen = Color(0xFF97F0FF)
val OnSecondaryContainerGreen = Color(0xFF001F24)
val TertiaryBrown = Color(0xFF745A2E)
val OnTertiaryBrown = Color(0xFFFFFFFF)
val TertiaryContainerBrown = Color(0xFFFFDEAB)
val OnTertiaryContainerBrown = Color(0xFF271900)
val ErrorRed = Color(0xFFBA1A1A)
val OnErrorRed = Color(0xFFFFFFFF)
val ErrorContainerRed = Color(0xFFFFDAD6)
val OnErrorContainerRed = Color(0xFF410002)
val BackgroundWhite = Color(0xFFFFFBFF)
val OnBackgroundWhite = Color(0xFF201A1A)
val SurfaceWhite = Color(0xFFFFFBFF)
val OnSurfaceWhite = Color(0xFF201A1A)
val SurfaceVariantBeige = Color(0xFFF4DDDC)
val OnSurfaceVariantBeige = Color(0xFF524342)
val OutlineGray = Color(0xFF857372)
val InverseOnSurfacePink = Color(0xFFFBEEED)
val InverseSurfaceBlack = Color(0xFF362F2E)
val InversePrimaryLightRed = Color(0xFFFFB3B0)
val ShadowBlack = Color(0xFF000000)
val SurfaceTintRed = Color(0xFFB6212F)
val OutlineVariantLightGray = Color(0xFFD7C1C0)
val ScrimBlack = Color(0xFF000000)