name: Build AAR
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get Version Number
        id: version-number
        run: |
          VERSION=$(cat VERSION.md)
          echo ::set-output name=version::$VERSION
      - name: Get Build Date
        id: build-date
        run: echo ::set-output name=date::$(date +%Y-%m-%d)
      - name: Build AAR
        run: ./gradlew build
      - name: Upload AAR
        uses: actions/upload-artifact@v2
        with:
          name: my-aar-${{ steps.version-number.outputs.version }}-${{ steps.build-date.outputs.date }}.aar
          path: app/build/outputs/aar/
      - name: Create branch with version tag
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: peter-evans/create-or-update-branch@v3
        with:
          branch: release/v{{ steps.version-number.outputs.version }}
      - name: Create tag with version
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: peter-evans/create-or-update-tag@v2
        with:
          tag: v{{ steps.version-number.outputs.version }}
          message: Release version v{{ steps.version-number.outputs.version }}
