name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Setup Gradle
        run: |
          mkdir ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
          echo "org.gradle.jvmargs=-Xmx3072m" >> ~/.gradle/gradle.properties

      - name: set environment variables
        run: |
          echo ::set-env name=version::$(cat VERSION.md)
          echo ::set-env name=date::$(date +%Y-%m-%d)

      - name: Give gradlew execute permissions
        run: chmod +x gradlew

      - name: Build AAR
        run: env version=${ version } ./gradlew :app:assembleRelease

      - name: Upload AAR
        uses: actions/upload-artifact@v2
        with:
          name: paguei-${{ env.version }}-${{ env.date }}.aar
          path: app/build/outputs/aar/

      - name: Build APK
        run: env version=${ version } ./gradlew :app:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: paguei-${{ env.version }}-${{ env.date }}.apk
          path: app/build/outputs/apk/

      - name: Create Branch Release
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ vars.TOKEN }}
        with:
          branch: release/${{ env.version }}
          sha: '${{ github.event.pull_request.head.sha }}'
