name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Setup Gradle
        run: |
          mkdir ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
          echo "org.gradle.jvmargs=-Xmx3072m" >> ~/.gradle/gradle.properties

      - name: Extract version from VERSION.md
        run: echo "version=$(cat VERSION.md)" >> $GITHUB_ENV

      - name: Get Build Date
        run: echo ::set-output name=date::$(date +%Y-%m-%d)

      - name: Give gradlew execute permissions
        run: chmod +x gradlew

      - name: Build AAR
        run: ./gradlew :app:assembleRelease

      - name: Upload AAR
        uses: actions/upload-artifact@v2
        with:
          name: paguei-${{ steps.version-number.outputs.version }}-${{ steps.build-date.outputs.date }}.aar
          path: app/build/outputs/aar/

      - name: Build APK
        run: ./gradlew :app:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: paguei-${{ steps.version-number.outputs.version }}-${{ steps.build-date.outputs.date }}.apk
          path: app/build/outputs/apk/

      - name: Create new branch with version
        run: |
          export version=$(cat VERSION.md)
          git checkout -b "release/$version"
          git add -f app/build/outputs/
          git add -f library/build/outputs/
          git commit -m "Release version $version"
          git push -u origin "release/$version"