name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Setup Gradle
        run: |
          mkdir ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
          echo "org.gradle.jvmargs=-Xmx3072m" >> ~/.gradle/gradle.properties

      - name: Extract version from VERSION.md
        run: echo "version=$(cat VERSION.md)" >> $GITHUB_ENV

      - name: Give gradlew execute permissions
        run: chmod +x gradlew

      - name: Build AAR
        run: ./gradlew :library:assembleRelease

      - name: Build APK
        run: ./gradlew :app:assembleRelease

      - name: Create new branch with version
        run: |
          export version=$(cat VERSION.md)
          git checkout -b "release/$version"
          git add app/build/outputs/
          git add library/build/outputs/
          git commit -m "Release version $version"
          git push -u origin "release/$version"