name: Create changelog

on:
  push:
    branches:
      - master
      - develop

jobs:
  create_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get last tag
        run: echo "LAST_TAG=$(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags | head -n 1)" >> $GITHUB_ENV

      - name: Retrieve commits and version
        run: |
          COMMITS=$(git log --pretty=format:"- %s" $LAST_TAG..HEAD)
          TAG=$(git describe --tags --abbrev=0)
          echo "Commits: $COMMITS"
          echo "Tag: $TAG"

      - name: Generate changelog
        run: |
          # Check if CHANGELOG.md already exists
          if [ -f CHANGELOG.md ]; then
            # Retrieve previous content
            PREVIOUS_CONTENT=$(cat CHANGELOG.md)
            # Add new version and commits to previous content
            echo "## VERSION ($tag)" >> CHANGELOG.md
            echo "$COMMITS" >> CHANGELOG.md
            echo "$PREVIOUS_CONTENT" >> CHANGELOG.md
          else
            # Create new CHANGELOG.md with version and commits
            echo "## VERSION ($tag)" >> CHANGELOG.md
            echo "$COMMITS" >> CHANGELOG.md
          fi

      - name: Create and push changelog
        run: |
          git add CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update changelog"
          git push origin main
