name: Build Application Release
on:
  push:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  JDK_VERSION: 11
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx3072m"
  APP_NAME: "Paguei"

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    name: Setup Environment
    outputs:
      has-exec-permissions: ${{ steps.set_permissions.outcome == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{ env.JDK_VERSION }}'

      - name: Give execution permissions to gradlew
        id: set_permissions
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        run: echo "org.gradle.daemon=false" >> $GITHUB_WORKSPACE/gradle.properties

  create_google_services_file:
    runs-on: ubuntu-latest
    name: Create Google Services File
    needs: setup_environment
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Create google-services release file
        run: |
          rm -f app/google-services.json
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Verify google-services.json
        run: |
          cat app/google-services.json
          grep -q '"package_name": "br.com.brunocarvalhs.paguei"' app/google-services.json || (echo "Package name not found in google-services.json" && exit 1)

  unit_tests:
    needs: [setup_environment, create_google_services_file]
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Unit tests
        run: ./gradlew testRelease --stacktrace
        env:
          HAS_EXEC_PERMISSIONS: ${{ needs.setup_environment.outputs.has-exec-permissions }}
          JDK_VERSION: ${{ env.JDK_VERSION }}
          ANDROID_SDK_TOOLS: ${{ env.ANDROID_SDK_TOOLS }}
          GRADLE_OPTS: ${{ env.GRADLE_OPTS }}

  android_lint:
    needs: [setup_environment, create_google_services_file]
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Android Lint
        run: ./gradlew lintRelease
        env:
          HAS_EXEC_PERMISSIONS: ${{ needs.setup_environment.outputs.has-exec-permissions }}
          JDK_VERSION: ${{ env.JDK_VERSION }}
          ANDROID_SDK_TOOLS: ${{ env.ANDROID_SDK_TOOLS }}
          GRADLE_OPTS: ${{ env.GRADLE_OPTS }}

  extract_version_and_date:
    runs-on: ubuntu-latest
    name: Extract Version and Date
    needs: setup_environment
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      date: ${{ steps.extract_date.outputs.date }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Extract version from VERSION.md
        id: extract_version
        run: echo "::set-output name=version::$(cat VERSION.md)"

      - name: Get Build Date
        id: extract_date
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

  build_apk:
    runs-on: ubuntu-latest
    name: Build APK
    needs: [setup_environment, unit_tests, android_lint, create_google_services_file, extract_version_and_date]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-APK-${{ needs.extract_version_and_date.outputs.version }}-${{ needs.extract_version_and_date.outputs.date }}
          path: app/build/outputs/apk/**/*.apk

  build_aab:
    runs-on: ubuntu-latest
    name: Build AAB
    needs: [setup_environment, unit_tests, android_lint, create_google_services_file, extract_version_and_date]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Build AAB
        run: ./gradlew bundleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-AAB-${{ needs.extract_version_and_date.outputs.version }}-${{ needs.extract_version_and_date.outputs.date }}
          path: app/build/outputs/bundle/**/*.aab
