name: Build Application Release
on:
  push:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    name: Setup Environment
    outputs:
      enable_unit_tests: true
      enable_android_lint: true
      enable_build_apk: true
      enable_build_aab: true
      enable_firebase_publish: false
      jdk_version: 11
      gradle_opts: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx3072m"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        run: echo "org.gradle.daemon=false" >> $GITHUB_WORKSPACE/gradle.properties

  unit_tests:
    needs: setup_environment
    runs-on: ubuntu-latest
    if: ${{ needs.setup_environment.outputs.enable_unit_tests }}
    name: Unit Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Create google-services release file
        run: |
          rm -f app/google-services.json
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Unit tests
        run: ./gradlew testRelease --stacktrace
        env:
          JDK_VERSION: ${{ needs.setup_environment.outputs.jdk_version }}
          ANDROID_SDK_TOOLS: ${{ env.ANDROID_SDK_TOOLS }}
          GRADLE_OPTS: ${{ needs.setup_environment.outputs.gradle_opts }}

  android_lint:
    needs: setup_environment
    runs-on: ubuntu-latest
    if: ${{ needs.setup_environment.outputs.enable_android_lint }}
    name: Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Create google-services release file
        run: |
          rm -f app/google-services.json
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Android Lint
        run: ./gradlew lintRelease
        env:
          JDK_VERSION: ${{ needs.setup_environment.outputs.jdk_version }}
          ANDROID_SDK_TOOLS: ${{ env.ANDROID_SDK_TOOLS }}
          GRADLE_OPTS: ${{ needs.setup_environment.outputs.gradle_opts }}

  build_apk:
    needs: [unit_tests, android_lint]
    runs-on: ubuntu-latest
    if: ${{ needs.setup_environment.outputs.enable_build_apk }}
    name: Build APK
    env:
      KEYSTORE_ALIAS: ${{ secrets.ALIAS }}
      KEY_PASSWORD: ${{ secrets.PASSWORD_ALIAS }}
      KEYSTORE_PASSWORD: ${{ secrets.PASSWORD_KEY }}
      APP_NAME: "Paguei"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Create google-services release file
        run: |
          rm -f app/google-services.json
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-apk
          path: app/build/outputs/apk/**/*.apk

  build_aab:
    needs: [unit_tests, android_lint]
    runs-on: ubuntu-latest
    if: ${{ needs.setup_environment.outputs.enable_build_aab }}
    name: Build AAB
    env:
      KEYSTORE_ALIAS: ${{ secrets.ALIAS }}
      KEY_PASSWORD: ${{ secrets.PASSWORD_ALIAS }}
      KEYSTORE_PASSWORD: ${{ secrets.PASSWORD_KEY }}
      APP_NAME: "Paguei"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Create google-services release file
        run: |
          rm -f app/google-services.json
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Build AAB
        run: ./gradlew bundleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-aab
          path: app/build/outputs/bundle/**/*.aab

  publish:
    needs: [build_apk, build_aab]
    runs-on: ubuntu-latest
    if: ${{ needs.setup_environment.outputs.enable_firebase_publish }}
    name: Publish
    env:
      APP_NAME: "Paguei"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Get App Version
        run: echo "::set-env name=version::$(cat VERSION.md)"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.APP_NAME }} v${{ env.version }}
