name: Android Tests

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  JDK_VERSION: 11
  ANDROID_SDK_TOOLS: latest
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx3072m"
  APP_NAME: "Paguei"

jobs:
  checkout-and-setup:
    runs-on: ubuntu-24.04
    name: Checkout and Setup Environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{ env.JDK_VERSION }}'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create local.properties
        run: |
          echo "sdk.dir=${{ env.ANDROID_HOME }}" > local.properties
      
      - name: Create google-services.json
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json
      
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Upload Workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: ./
          
  unit-tests:
    runs-on: ubuntu-24.04
    name: Run Unit Tests
    needs: checkout-and-setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Create google-services.json
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebug
        env:
          GRADLE_OPTS: ${{ env.GRADLE_OPTS }}

      - name: Comment Failure
        if: ${{ failure() }}
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Ops, encontrado falhas nos testes unitários, por favor precisa corrigir."
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          reactions: "-1 | confused"

      - name: Comment Success
        if: ${{ success() }}
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Todos os testes unitários passaram com sucesso! Bom trabalho."
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          reactions: "+1"

  lint-check:
    runs-on: ubuntu-24.04
    name: Run Lint Check
    needs: checkout-and-setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Create google-services.json
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Run Lint
        run: ./gradlew lintDebug
        env:
          GRADLE_OPTS: ${{ env.GRADLE_OPTS }}

      - name: Comment Failure
        if: ${{ failure() }}
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Ops, encontrado falhas no lint, por favor precisa corrigir."
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          reactions: "-1 | confused"

      - name: Comment Success
        if: ${{ success() }}
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Todos os lints passaram com sucesso! Bom trabalho."
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          reactions: "+1"
          
  build:
    runs-on: ubuntu-24.04
    name: Build
    needs: [unit-tests, lint-check]
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Create google-services.json
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Build APK Debug
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-apk-debug
          path: app/build/outputs/apk/debug/*.apk
